branches:
  only:
  - master
  - /^v\d.*/

language: python
dist: xenial
sudo: true
python:
  - "3.6"
  - "3.7"
matrix:
  include:
  - python: "3.7"
    env: TOXENV=py37-flake8

cache: pip
addons:
  apt:
    packages:

install:
  - pip install tox-travis codecov
script:
  - tox -- -m "not integration"
after_success:
- codecov
